[package]
name = "starter"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = "1.0.0-rc.2"
risc0-circuit-rv32im = "1.0.0-rc.2"
risc0-zkp = "1.0.0-rc.2"
serde_json = "1.0.91"
serde = "1.0"
env_logger = "0.10.0"